[package]
name = "records"
edition.workspace = true
publish = false

# [lib]
# crate-type = ["cdylib", "rlib"]

[dependencies]
base64ct.workspace = true
serde_json.workspace = true
test-utils.workspace = true
tokio.workspace = true
vercre-dwn = { path = "../.." }

[dev-dependencies]
