[package]
name = "vercre-dwn"
description = "Decentralized Web Node (DWN)"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
ciborium = "0.2.2"
cid = "0.11.1"
multihash-codetable = { version = "0.1.3", features = ["sha2"] }
serde.workspace = true
serde_json.workspace = true
surrealdb.workspace = true
tokio.workspace = true

[dev-dependencies]

[workspace]
# members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["authentication", "cryptography", "data-structures"]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/dwn"
rust-version = "1.80"
version = "0.1.0-alpha.1"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.89"
assert_let_bind = "0.1.1"
async-trait = "0.1.82"
axum = { version = "0.7.7", features = ["macros"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
base64ct = { version = "1.6.0", features = ["std"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["alloc"] }
sha2 = "0.10.8"
surrealdb = { version = "1.5.5", features = ["kv-mem"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
