[package]
name = "vercre-dwn"
description = "Decentralized Web Node (DWN)"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-recursion = "1.1.1"
base64ct.workspace = true
chrono = { version = "0.4.39", features = ["serde"] }
ciborium = "0.2.2"
cid.workspace = true
derive_more = { version = "1.0.0", features = ["display"] }
futures.workspace = true
hkdf = "0.12.4"
http.workspace = true
jsonschema = { version = "0.28.1", default-features = false, features = ["resolve-file"] }
libipld = "0.16.0"
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.8"
thiserror = "2.0.9"
tokio = { workspace = true, features = ["sync"] }
uuid = { version = "1.11.0", features = ["fast-rng", "v4"] }
vercre-did.workspace = true
vercre-infosec.workspace = true
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }

[dev-dependencies]
dwn-test.workspace = true
insta.workspace = true
rand.workspace = true
tokio.workspace = true

[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["data", "messaging", "didcomm", "identity", "verifiable"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/dwn"
rust-version = "1.85"
version = "0.1.0-alpha.1"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.95"
base64ct = { version = "1.6.0", features = ["std"] }
cid = "0.11.1"
dwn-test = { path = "crates/dwn-test" }
futures = "0.3.31"
http = "1.2.0"
insta = { version = "1.41.1", features = ["redactions", "yaml"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.134", features = ["alloc"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "time"] }
vercre-did = { git = "https://github.com/vercre/did.git" }
vercre-infosec = { git = "https://github.com/vercre/infosec.git" }

[patch."https://github.com/vercre/infosec.git"]
vercre-infosec = { path = "../infosec" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
