[package]
name = "credibil-dwn"
description = "Decentralized Web Node (DWN)"
readme = "README.md"
authors.workspace = true
categories = ["web-programming", "embedded", "database"]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords = ["decentralized", "didcomm", "web", "node", "storage"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
# default = ["client"]
default = ["client", "server"]
# Includes DWN client features such as request builders.
client = []
# Includes DWN server features such handlers.
server = ["dep:async-recursion", "dep:tokio"]

[dependencies]
aes-gcm = "0.10.3"
anyhow.workspace = true
async-recursion = { version = "1.1.1", optional = true }
base64ct.workspace = true
cfg-if = "1.0.0"
chrono = { version = "0.4.39", features = ["serde"] }
ciborium = "0.2.2"
cid.workspace = true
credibil-did.workspace = true
credibil-infosec.workspace = true
derive_more = { version = "2.0.1", features = ["display"] }
ed25519-dalek.workspace = true
futures.workspace = true
hkdf = "0.12.4"
http.workspace = true
ipld-core = "0.4.1"
jsonschema = { version = "0.29.0", default-features = false, features = ["resolve-file"] }
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
rand.workspace = true
serde.workspace = true
serde_ipld_dagcbor = "0.6.1"
serde_json.workspace = true
sha2.workspace = true
thiserror = "2.0.11"
tokio = { workspace = true, optional = true }
ulid = "1.2.0"
uuid = { version = "1.13.1", features = ["fast-rng", "v4"] }
x25519-dalek.workspace = true
zeroize = "1.8.1"

[dev-dependencies]
blockstore = "0.7.1"
test-node.workspace = true

[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://credibil.io"
license = "MIT OR Apache-2.0"
repository = "https://github.com/credibil/dwn"
rust-version = "1.85"
version = "0.1.0-beta.1"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.95"
base64ct = { version = "1.6.0", features = ["std"] }
cid = { version = "0.11.1", features = ["alloc"] }
credibil-did = "0.1.0"
credibil-infosec = "0.1.0"
credibil-dwn = { path = "." }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
futures = "0.3.31"
http = "1.2.0"
multibase = "0.9"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["alloc"] }
sha2 = "0.10.8"
test-node = { path = "crates/test-node" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time"] }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }

# [patch."https://github.com/credibil/infosec.git"]
# credibil-infosec = { path = "../infosec" }

[profile.release]
# optimize for small code size
lto = true
opt-level = "s"
strip = true
