[package]
name = "credibil-dwn"
description = "Decentralized Web Node (DWN)"
readme = "README.md"
authors.workspace = true
categories = ["web-programming", "embedded", "database"]
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords = ["decentralized", "didcomm", "web", "node", "storage"]
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[features]
default = ["client", "server"]
# Includes DWN client features such as request builders.
client = []
# Includes DWN server features such handlers.
server = ["dep:async-recursion", "dep:tokio"]

[dependencies]
aes-gcm = "0.10.3"
anyhow.workspace = true
async-recursion = { version = "1.1.1", optional = true }
base64ct.workspace = true
bytes = "1.10.1"
cfg-if = "1.0.0"
chrono = { version = "0.4.40", features = ["serde"] }
ciborium = "0.2.2"
cid.workspace = true
credibil-did.workspace = true
credibil-infosec.workspace = true
datastore.workspace = true
derive_more = { version = "2.0.1", features = ["display"] }
ed25519-dalek.workspace = true
futures.workspace = true
hkdf = "0.12.4"
http.workspace = true
http-body = "1.0.1"
http-body-util = "0.1"
ipld-core = "0.4.2"
jsonschema = { version = "0.29.1", default-features = false, features = ["resolve-file"] }
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
rand.workspace = true
serde.workspace = true
serde_ipld_dagcbor = "0.6.3"
serde_json.workspace = true
sha2.workspace = true
thiserror = "2.0.12"
tokio = { workspace = true, optional = true }
ulid = "1.2.1"
uuid = { version = "1.16.0", features = ["fast-rng", "v4"] }
x25519-dalek.workspace = true
zeroize = "1.8.1"

[dev-dependencies]
async-nats = "0.40.0"
axum = { version = "0.8.3", features = ["macros"] }
blockstore = "0.7.1"
credibil-dwn.workspace = true
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
multibase.workspace = true
reqwest = { version = "0.12.15", features = ["json"] }
x25519-dalek = { workspace = true, features = ["static_secrets"] }

[[example]]
name = "axum"
path = "examples/axum.rs"
# required-features = ["client", "server"]

[[example]]
name = "hyper"
path = "examples/hyper.rs"
# required-features = ["client", "server"]

# -----------------------------------------------
# Workspace
# -----------------------------------------------
[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://credibil.io"
license = "MIT OR Apache-2.0"
repository = "https://github.com/credibil/dwn"
rust-version = "1.86"
version = "0.1.2"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.97"
base64ct = { version = "1.7.3", features = ["std"] }
cid = { version = "0.11.1", features = ["alloc"] }
credibil-did = "0.1.2"
credibil-dwn = { path = "." }
credibil-infosec = "0.1.2"
datastore = { path = "./crates/datastore" }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
futures = "0.3.31"
http = "1.3.1"
multibase = "0.9.1"
rand = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
sha2 = "0.10.8"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "time"] }
x25519-dalek = "2.0.1"

[patch.crates-io]
credibil-did = { path = "../did" }
# credibil-did = { git = "https://github.com/credibil/did.git" }
credibil-infosec = { path = "../infosec" }
# credibil-infosec = { git = "https://github.com/credibil/infosec.git" }

[profile.release]
# optimize for small code size
lto = true
opt-level = "s"
strip = true

[profile.test]
opt-level = 1
# debug-assertions = true
