[package]
name = "vercre-dwn"
description = "Decentralized Web Node (DWN)"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-recursion = "1.1.1"
async-trait.workspace = true
base64ct.workspace = true
chrono.workspace = true
ciborium = "0.2.2"
cid.workspace = true
derive_more = { workspace = true, features = ["display"] }
futures.workspace = true
http.workspace = true
jsonschema = { version = "0.26.1", default-features = false, features = ["resolve-file"] }
libipld.workspace = true
multihash-codetable.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.3"
tokio = { workspace = true, features = ["sync"] }
vercre-did.workspace = true
vercre-infosec.workspace = true

[dev-dependencies]
dwn-test.workspace = true
insta.workspace = true
rand.workspace = true
tokio.workspace = true

[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["data", "messaging", "didcomm", "identity", "verifiable"]
edition = "2021"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/dwn"
rust-version = "1.80"
version = "0.1.0-alpha.1"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.93"
assert_let_bind = "0.1.1"
async-trait = "0.1.83"
axum = { version = "0.7.9", features = ["macros"] }
axum-extra = { version = "0.9.6", features = ["typed-header"] }
base64ct = { version = "1.6.0", features = ["std"] }
chrono = { version = "0.4.38", features = ["serde"] }
cid = "0.11.1"
derive_more = "1.0.0"
dwn-test = { path = "crates/dwn-test" }
futures = "0.3.31"
http = "1.1.0"
insta = { version = "1.41.1", features = ["redactions", "yaml"] }
libipld = "0.16.0"
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133", features = ["alloc"] }
sha2 = "0.10.8"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "time"] }
vercre-did = { git = "https://github.com/vercre/did.git" }
vercre-infosec = { git = "https://github.com/vercre/infosec.git" }

[patch."https://github.com/vercre/infosec.git"]
vercre-infosec = { path = "../infosec" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
