[workspace]
members = ["dwn-node", "dwn-msg", "crates/*", "examples/*"]
resolver = "2"

[workspace.package]
authors = ["Vercre"]
categories = ["data", "messaging", "didcomm", "identity", "verifiable"]
edition = "2024"
exclude = [".*", "/docs", "snapshots/"]
homepage = "https://vercre.io"
keywords = ["credentials", "decentralized", "identity", "openid", "verifiable"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/vercre/dwn"
rust-version = "1.85"
version = "0.1.0-alpha.1"

[workspace.lints.rust]
missing_docs = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# clippy::all = correctness, suspicious, style, complexity, perf
# not using (yet) -Dclippy::restriction
all = "warn"
pedantic = "warn"
nursery = "warn"

[workspace.dependencies]
anyhow = "1.0.95"
base64ct = { version = "1.6.0", features = ["std"] }
cid = "0.11.1"
dwn-msg = { path = "dwn-msg" }
dwn-node = { path = "dwn-node" }
dwn-test = { path = "crates/dwn-test" }
dwn-types = { path = "crates/dwn-types" }
futures = "0.3.31"
http = "1.2.0"
insta = { version = "1.42.0", features = ["redactions", "yaml"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.135", features = ["alloc"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time"] }
vercre-did = { git = "https://github.com/vercre/did.git" }
vercre-infosec = { git = "https://github.com/vercre/infosec.git" }

# [patch."https://github.com/vercre/infosec.git"]
# vercre-infosec = { path = "../infosec" }

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
