[toolchain]
# channel = "stable"
# channel = "nightly"
channel = "nightly-2025-01-25"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "wasm32-wasip2",
]
