[package]
name = "records"
edition.workspace = true
publish = false

# [lib]
# crate-type = ["cdylib", "rlib"]

[dependencies]
base64ct.workspace = true
credibil-dwn.workspace = true
serde_json.workspace = true
test-node.workspace = true
tokio.workspace = true

[dev-dependencies]
