[package]
name = "test-utils"
description = "Test utilities"
edition.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
async-trait = "0.1.83"
base64ct.workspace = true
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
multibase = "0.9"
prqlc.workspace = true
serde.workspace = true
serde_json.workspace = true
surrealdb = { version = "1.5.5", features = ["kv-mem"] }
vercre-dwn = { path = "../.." }
vercre-infosec.workspace = true

[dev-dependencies]
