[package]
name = "test-utils"
edition.workspace = true
publish = false
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
async-trait = "0.1.83"
base64ct.workspace = true
blockstore = "0.7.0"
ciborium = "0.2.2"
cid = { workspace = true, features = ["alloc"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
insta.workspace = true
libipld = "0.16.0"
libipld-cbor = "0.16.0"
multibase = "0.9"
multihash = "0.18.0"
# multihash = { version = "0.19.2", default-features = false, features = ["multihash-impl"] }
multihash-codetable.workspace = true
prqlc.workspace = true
serde.workspace = true
serde_json.workspace = true
surrealdb = { version = "1.5.5", features = ["kv-mem"] }
vercre-dwn = { path = "../.." }
vercre-infosec.workspace = true

[dev-dependencies]
