[package]
name = "datastore"
edition.workspace = true
publish = false
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
async-nats = "0.39.0"
base64ct.workspace = true
blockstore = "0.7.1"
chrono = { version = "0.4.39", features = ["serde"] }
ciborium = "0.2.2"
cid.workspace = true
ed25519-dalek.workspace = true
futures.workspace = true
ipld-core = "0.4.1"
multibase.workspace = true
multihash-codetable = { version = "0.1.4", features = ["sha2"] }
rand.workspace = true
serde.workspace = true
serde_ipld_dagcbor = "0.6.1"
serde_json.workspace = true
sha2.workspace = true
x25519-dalek.workspace = true
