
# cargo-vet audits file

[[wildcard-audits.credibil-dwn]]
who = "Andrew Weston <andrewweston@propellerhead.co.nz>"
criteria = "safe-to-deploy"
user-id = 1 # Andrew Weston (andrewweston)
start = "2024-01-01"
end = "2025-01-01"
notes = """
Vercre uses `<publisher>` crates.io account to automate
publication of this crate from CI. This repository requires all PRs are reviewed
by a Vercre maintainer and it owned by Vercre itself.
"""

