
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.credibil-core]
audit-as-crates-io = true

[policy.credibil-dwn]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aes-kw]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.async-nats]]
version = "0.43.0"
criteria = "safe-to-deploy"

[[exemptions.async-recursion]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.axum]]
version = "0.8.4"
criteria = "safe-to-run"

[[exemptions.axum-core]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.axum-macros]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.base-x]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.4"
criteria = "safe-to-deploy"

[[exemptions.blake2b_simd]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.blake2s_simd]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.blake3]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.blockstore]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.borrow-or-share]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.bytecount]]
version = "0.6.9"
criteria = "safe-to-deploy"

[[exemptions.cbor4ii]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.38"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.cid]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.core2]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.credibil-core]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.credibil-dwn]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding-macro]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.data-encoding-macro-internal]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ecies]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.email_address]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.fancy-regex]]
version = "0.16.2"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.fluent-uri]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.fraction]]
version = "0.15.3"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.64"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.ipld-core]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.81"
criteria = "safe-to-deploy"

[[exemptions.jsonschema]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.k256]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.keccak]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-core]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-gen-ecmult]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-gen-genmult]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.28"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-run"

[[exemptions.multihash]]
version = "0.19.3"
criteria = "safe-to-deploy"

[[exemptions.multihash-codetable]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.multihash-derive]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.multihash-derive-impl]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.nkeys]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.50.1"
criteria = "safe-to-run"

[[exemptions.nuid]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.num-cmp]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.outref]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.17"
criteria = "safe-to-deploy"

[[exemptions.referencing]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.ripemd]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.32"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.6"
criteria = "safe-to-deploy"

[[exemptions.ryu-js]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.27"
criteria = "safe-to-deploy"

[[exemptions.serde_ipld_dagcbor]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.serde_json_canonicalizer]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.serde_nanos]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signatory]]
version = "0.27.1"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.strobe-rs]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-run"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.time]]
version = "0.3.44"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.24"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.3"
criteria = "safe-to-deploy"

[[exemptions.tokio-websockets]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.toml_parser]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.tryhard]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.ulid]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.19"
criteria = "safe-to-deploy"

[[exemptions.unsigned-varint]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.18.1"
criteria = "safe-to-deploy"

[[exemptions.uuid-simd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.vsimd]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.104"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"
